nmap { '<c-1>', '<cmd>tabnext 1<cr>' }
nmap { '<c-2>', '<cmd>tabnext 2<cr>' }
nmap { '<c-3>', '<cmd>tabnext 3<cr>' }
nmap { '<c-4>', '<cmd>tabnext 4<cr>' }
nmap { '<c-5>', '<cmd>tabnext 5<cr>' }
nmap { '<c-6>', '<cmd>tabnext 6<cr>' }
nmap { '<c-7>', '<cmd>tabnext 7<cr>' }
nmap { '<c-8>', '<cmd>tabnext 8<cr>' }
nmap { '<c-9>', '<cmd>tabnext 9<cr>' }
nmap { '<c-0>', '<cmd>tabnext 10<cr>' }
